<div style="text-align: center;">
<h1>The University of North Carolina at Chapel Hill</h1>
<h1>Comp 555 BioAlgorithms - Spring 2019</h1>
<h1 style="font-size: 250%;">Final Exam</h1>
<h1>Friday May 3, 2019</h1>
<h2>8:00am-11:00am (180 mins)</h2>
</div>
<br>

**Instructions:** Answer all questions ***using the cells*** provided. Feel free to add additional cells to your notebook, but there is no guarantee that they will be considered when grading. If any question seems unclear or appears to lack sufficient information, state a reasonable assumption in the cell provided for your answer and proceed. This test is open-book, open-note, and open-internet rosources. However, ***you cannot use the internet as a means for communication with anyone interactively***. This means no instant messaging, no social-media communication, no virtual whiteboards, and no shared web-documents are allowed. In other words, any attempt to communicate with another person, other than the instructors, during the test will be considered an honor-code violation.

---
**Problem #1:** (10 points) Given the following DNA alignment scoring matrix:

<table style="border-collapse: collapse; border: 1px solid black; background-color: white;">
    <tr style="background-color: white;">
        <th>&delta;</th>
        <th style="border: 1px solid black;">  A </th>
        <th style="border: 1px solid black;">  C </th>
        <th style="border: 1px solid black;">  G </th>
        <th style="border: 1px solid black;">  T </th>
    </tr>
    <tr style="background-color: white;">
        <th style="border: 1px solid black;">   A  </th>
        <td style="background-color: #f0fff0;">  2 </td>
        <td style="background-color: #fff0f0;"> -2 </td>
        <td style="background-color: #fff0f0;"> -1 </td>
        <td style="background-color: #fff0f0;"> -2 </td>
    </tr>
    <tr style="background-color: white;">
        <th style="border: 1px solid black;">   C  </th>
        <td style="background-color: #fff0f0;"> -2 </td>
        <td style="background-color: #f0fff0;">  2 </td>
        <td style="background-color: #fff0f0;"> -2 </td>
        <td style="background-color: #fff0f0;"> -1 </td>
    </tr>
    <tr style="background-color: white;">
        <th style="border: 1px solid black;">   G  </th>
        <td style="background-color: #fff0f0;"> -1 </td>
        <td style="background-color: #fff0f0;"> -2 </td>
        <td style="background-color: #f0fff0;">  2 </td>
        <td style="background-color: #fff0f0;"> -2 </td>
    </tr>
    <tr style="background-color: white;">
        <th style="border: 1px solid black;">   T  </th>
        <td style="background-color: #fff0f0;"> -2 </td>
        <td style="background-color: #fff0f0;"> -1 </td>
        <td style="background-color: #fff0f0;"> -2 </td>
        <td style="background-color: #f0fff0;">  2 </td>
    </tr>
</table>

and an *InDel* penalty of -3, what is the best *global alignment score*, and alignment for the following DNA sequences?

    v = "AACACAAACTGAGCCCCTACCCCAAATTAGAACTGGATCTGGACCCTTCCATTCATTAGTCAGGGGGTCCTTCCATTTTACCAATGCATA"
    w = "AAAAACACAAACTGAGCCCCTACCCCAAATTAGGACTGGATCTGGACCCTTCCATTCATTAGTCAGGGGGTCCTTCTATTTTACCAATGT"

In the space provided below give a ***number for your global alignment score*** and ***show an alignment*** in the style of the Alignment() method given in class (Lecture 18, slide 27). 

In [1]:
import numpy
v = "AACACAAACTGAGCCCCTACCCCAAATTAGAACTGGATCTGGACCCTTCCATTCATTAGTCAGGGGGTCCTTCCATTTTACCAATGCATA"
w = "AAAAACACAAACTGAGCCCCTACCCCAAATTAGGACTGGATCTGGACCCTTCCATTCATTAGTCAGGGGGTCCTTCTATTTTACCAATGT"

def Alignment(b,v,w,i,j):
    if ((i == 0) and (j == 0)):
        return ['','']
    if (b[i,j] == 3):
        result = Alignment(b,v,w,i-1,j-1)
        result[0] += v[i-1]
        result[1] += w[j-1]
        return result
    if (b[i,j] == 2):
        result = Alignment(b,v,w,i,j-1)
        result[0] += "_"
        result[1] += w[j-1]
        return result
    if (b[i,j] == 1):
        result = Alignment(b,v,w,i-1,j)
        result[0] += v[i-1]
        result[1] += "_"
        return result

def GlobalAlign(v, w, scorematrix, indel):
    s = numpy.zeros((len(v)+1,len(w)+1), dtype="int32")
    b = numpy.zeros((len(v)+1,len(w)+1), dtype="int32")
    for i in range(0,len(v)+1):
        for j in range(0,len(w)+1):
            if (j == 0):
                if (i > 0):
                    s[i,j] = s[i-1,j] + indel
                    b[i,j] = 1
                continue
            if (i == 0):
                s[i,j] = s[i,j-1] + indel
                b[i,j] = 2
                continue
            score = s[i-1,j-1] + scorematrix[v[i-1],w[j-1]]
            vskip = s[i-1,j] + indel
            wskip = s[i,j-1] + indel
            s[i,j] = max(vskip, wskip, score)
            if (s[i,j] == vskip):
                b[i,j] = 1
            elif (s[i,j] == wskip):
                b[i,j] = 2
            else:
                b[i,j] = 3
    return (s, b)

match = {('A','A'):  2, ('A','C'): -2, ('A','G'): -1, ('A','T'): -2,
         ('C','A'): -2, ('C','C'):  2, ('C','G'): -2, ('C','T'): -1,
         ('G','A'): -1, ('G','C'): -2, ('G','G'):  2, ('G','T'): -2,
         ('T','A'): -2, ('T','C'): -1, ('T','G'): -2, ('T','T'):  2}

# v = "TTCCGAGCGTTA"
# w = "TTTCAGGTTA"

s, b = GlobalAlign(v,w,match,-3)
print("s\n",s)
print("b\n",b)
print("Best score =", s[-1,-1])
align = Alignment(b,v,w,b.shape[0]-1,b.shape[1]-1)
print("v =", align[0])
print("w =", align[1])

s
 [[   0   -3   -6 ... -264 -267 -270]
 [  -3    2   -1 ... -259 -262 -265]
 [  -6   -1    4 ... -254 -257 -260]
 ...
 [-264 -259 -254 ...  146  151  153]
 [-267 -262 -257 ...  143  148  153]
 [-270 -265 -260 ...  140  145  150]]
b
 [[0 2 2 ... 2 2 2]
 [1 3 2 ... 2 2 2]
 [1 1 3 ... 2 2 2]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 3]
 [1 1 1 ... 1 1 1]]
Best score = 150
v = AA___CACAAACTGAGCCCCTACCCCAAATTAGAACTGGATCTGGACCCTTCCATTCATTAGTCAGGGGGTCCTTCCATTTTACCAATGCATA
w = AAAAACACAAACTGAGCCCCTACCCCAAATTAGGACTGGATCTGGACCCTTCCATTCATTAGTCAGGGGGTCCTTCTATTTTACCAATG__T_


---
**Problem #2:** (10 points) Find the longest common subsequence between the <b>v</b> and <b>w</b> sequences given in **Problem #1**. Use it to find the minimum edit distance between these two sequences.

In [2]:
match = {('A','A'):  2, ('A','C'): -2, ('A','G'): -1, ('A','T'): -2,
         ('C','A'): -2, ('C','C'):  2, ('C','G'): -2, ('C','T'): -1,
         ('G','A'): -1, ('G','C'): -2, ('G','G'):  2, ('G','T'): -2,
         ('T','A'): -2, ('T','C'): -1, ('T','G'): -2, ('T','T'):  2}

def LocalAlign(v, w, scorematrix, indel):
    s = numpy.zeros((len(v)+1,len(w)+1), dtype="int32")
    b = numpy.zeros((len(v)+1,len(w)+1), dtype="int32")
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            if (j == 0):
                if (i > 0):
                    s[i,j] = max(s[i-1,j] + indel, 0)
                    b[i,j] = 1
                continue
            if (i == 0):
                s[i,j] = max(s[i,j-1] + indel, 0)
                b[i,j] = 2
                continue
            score = s[i-1,j-1] + scorematrix[v[i-1],w[j-1]]
            vskip = s[i-1,j] + indel
            wskip = s[i,j-1] + indel
            s[i,j] = max(vskip, wskip, score, 0)
            if (s[i,j] == vskip):
                b[i,j] = 1
            elif (s[i,j] == wskip):
                b[i,j] = 2
            elif (s[i,j] == score):
                b[i,j] = 3
            else:
                b[i,j] = 0
    return (s, b)

s, b = LocalAlign(v,w,match,-7)
print(s)
print()
print(b)

def locBackTrack(i, j, score):
    # v is i and w is j
    vstart = i
    wstart = j
    path = [(i, j)]
    val = score[i, j]
    x = i
    y = j
    while val > 0:
        left = score[vstart-1, wstart]
        diag = score[vstart-1, wstart-1]
        top = score[vstart, wstart - 1]
        val = max(left, diag, top)
        if val == 0:
            break
        if val == left:
            vstart -= 1
        elif val == diag:
            vstart -= 1
            wstart -= 1
        elif val == top:
            wstart -= 1
        path.append((vstart, wstart))
    return [vstart, i, wstart, j], path
    
    
# we will create a function which will search for the highest score and backtrack from there
def LocalFinding(v, w, scores, backtrack):
    maxVal = -10000
    loc = (0, 0)
    for i in range(scores.shape[0]):
        for j in range(scores.shape[1]):
            if scores[i, j] > maxVal:
                maxVal = scores[i, j]
                loc = (i, j)
    
    # backtrack from our located position
#     align = LocalAlignCreate(backtrack, scores, v, w, loc[0], loc[1])
    return loc

s, b = LocalAlign(v, w, match, -3)
loc = LocalFinding(v, w, s, b)
ranges, path = locBackTrack(loc[0], loc[1], s)
print ("v:", ranges[0], ":", ranges[1], v[ranges[0]:ranges[1]])
print ("w:", ranges[2], ":", ranges[3], w[ranges[2]:ranges[3]])
print ("score:", s[loc[0], loc[1]])
print (path)

[[  0   0   0 ...   0   0   0]
 [  0   2   2 ...   0   0   0]
 [  0   2   4 ...   0   0   0]
 ...
 [  0   2   2 ... 143 152 158]
 [  0   0   0 ... 136 145 154]
 [  0   2   2 ... 129 138 147]]

[[0 0 0 ... 0 0 0]
 [0 3 3 ... 0 0 0]
 [0 3 3 ... 3 0 0]
 ...
 [0 3 3 ... 1 1 1]
 [0 0 3 ... 1 1 3]
 [0 3 3 ... 1 1 1]]
v: 1 : 86 ACACAAACTGAGCCCCTACCCCAAATTAGAACTGGATCTGGACCCTTCCATTCATTAGTCAGGGGGTCCTTCCATTTTACCAATG
w: 1 : 89 AAAACACAAACTGAGCCCCTACCCCAAATTAGGACTGGATCTGGACCCTTCCATTCATTAGTCAGGGGGTCCTTCTATTTTACCAATG
score: 166
[(86, 89), (85, 88), (84, 87), (83, 86), (82, 85), (81, 84), (80, 83), (79, 82), (78, 81), (77, 80), (76, 79), (75, 78), (74, 77), (73, 76), (72, 75), (71, 74), (70, 73), (69, 72), (68, 71), (67, 70), (66, 69), (65, 68), (64, 67), (63, 66), (62, 65), (61, 64), (60, 63), (59, 62), (58, 61), (57, 60), (56, 59), (55, 58), (54, 57), (53, 56), (52, 55), (51, 54), (50, 53), (49, 52), (48, 51), (47, 50), (46, 49), (45, 48), (44, 47), (43, 46), (42, 45), (41, 44), (40, 43), (39, 42), 

In [3]:
from numpy import *

def findLCS(v, w):
    score = zeros((len(v)+1,len(w)+1), dtype="int32")
    backt = zeros((len(v)+1,len(w)+1), dtype="int32")
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            # find best score at each vertex
            if (v[i-1] == w[j-1]):
                score[i,j], backt[i,j] = max((score[i-1,j-1]+1,3), (score[i-1,j],1), (score[i,j-1],2))
            else:
                score[i,j], backt[i,j] = max((score[i-1,j],1), (score[i,j-1],2))
    return score, backt
s, b = findLCS(v,w)
print("s\n",s)
print("b\n",b)
# for i in range(len(s)):
#     print("%10s %-20s    %12s %-20s" % ('' if i else 'score =', str(s[i]), '' if i else 'backtrack =', str(b[i])))

def LCS(b,v,i,j):
    print(i,j)
    if ((i == 0) or (j == 0)):
        return ''
    elif (b[i,j] == 3):
        return LCS(b,v,i-1,j-1) + v[i-1]
    elif (b[i,j] == 2):
        return LCS(b,v,i,j-1)
    else:
        return LCS(b,v,i-1,j)
# print(b.shape)
# print(s.shape)
print(LCS(b,v,b.shape[0]-1,b.shape[1]-1))

s
 [[ 0  0  0 ...  0  0  0]
 [ 0  1  1 ...  1  1  1]
 [ 0  1  2 ...  2  2  2]
 ...
 [ 0  1  2 ... 83 84 84]
 [ 0  1  2 ... 83 84 85]
 [ 0  1  2 ... 83 84 85]]
b
 [[0 0 0 ... 0 0 0]
 [0 3 3 ... 2 2 2]
 [0 3 3 ... 2 2 2]
 ...
 [0 3 3 ... 1 1 2]
 [0 1 1 ... 3 1 3]
 [0 3 3 ... 1 1 1]]
90 90
89 90
88 89
87 89
86 89
85 88
84 87
83 86
82 85
81 84
80 83
79 82
78 81
77 80
76 79
75 78
74 77
74 76
73 75
72 75
71 74
70 73
69 72
68 71
67 70
66 69
65 68
64 67
63 66
62 65
61 64
60 63
59 62
58 61
57 60
56 59
55 58
54 57
53 56
52 55
51 54
50 53
49 52
48 51
47 50
46 49
45 48
44 47
43 46
42 45
41 44
40 43
39 42
38 41
37 40
36 39
35 38
34 37
33 36
32 35
31 34
31 33
30 33
29 32
28 31
27 30
26 29
25 28
24 27
23 26
22 25
21 24
20 23
19 22
18 21
17 20
16 19
15 18
14 17
13 16
12 15
11 14
10 13
9 12
8 11
7 10
6 9
5 8
4 7
3 6
2 5
1 4
0 3
AACACAAACTGAGCCCCTACCCCAAATTAGACTGGATCTGGACCCTTCCATTCATTAGTCAGGGGGTCCTTCATTTTACCAATGT



---
**Problem #3.** (10 points) Suppose that you are given the following *constrained global alignment problem* for the sequences $v$ of length $n$, and $w$ of length $m$, which forces $v_i$ to be aligned with $w_j$. 

$$\begin{aligned}
v_1, v_2, ... v_{i-1}, &v_i, v_{i+1}, ... v_n \\
                       &\:|  \\
w_1, w_2, ... w_{j-1}, &w_j, w_{j+1}, ... w_m \\
\end{aligned}$$

How does the choice of $i$ and $j$ impact the performace of the algorithm? What choice of $i, j$ leads to the greatest speed up over a standard global alignment?

---
**Problem #4:** (5 points) Consider the following three peptide sequences:

        p1 = "KDPLTNEWKGPDPVLIW"
        p2 = "WILVPDPGKDPLTNEWK"
        p3 = "NEWKGPDPVLIWKDPLT"

What fraction of *each* petide's mass peaks are shared by all three peptides?

In [5]:
p1 = "KDPLTNEWKGPDPVLIW"
p2 = "WILVPDPGKDPLTNEWK"
p3 = "NEWKGPDPVLIWKDPLT"
Daltons = { 
    'A':  71, 'C': 103, 'D': 115, 'E': 129,
    'F': 147, 'G':  57, 'H': 137, 'I': 113,
    'K': 128, 'L': 113, 'M': 131, 'N': 114,
    'P':  97, 'Q': 128, 'R': 156, 'S':  87,
    'T': 101, 'V':  99, 'W': 186, 'Y': 163 
}


def TheoreticalSpectrum(peptide):
    # Generate every possible fragment of a peptide
    spectrum = set()
    for fragLength in range(1,len(peptide)+1):
        for start in range(0,len(peptide)-fragLength+1):
            seq = peptide[start:start+fragLength]
            spectrum.add(sum([Daltons[res] for res in seq]))
    return sorted(spectrum)

p1_spec = TheoreticalSpectrum(p1)
print("P1 Spec\n",p1_spec, len(p1_spec))

p2_spec = TheoreticalSpectrum(p2)
print("P2 Spec\n",p2_spec, len(p2_spec))

p3_spec = TheoreticalSpectrum(p3)
print("P3 Spec\n",p3_spec, len(p3_spec))


P1_P2 = set(p1_spec).intersection(set(p2_spec))
# print("set",len(set(p1_spec)))
# print(P1_P2, len(P1_P2))

frac_shared = set(p1_spec).intersection(set(p2_spec)).intersection(p3_spec)
print("Frac Shared\n",frac_shared, len(frac_shared))
print("Shared P1:", len(frac_shared)/len(p1_spec))
print("Shared P2:", len(frac_shared)/len(p2_spec))
print("Shared P3:", len(frac_shared)/len(p3_spec))


P1 Spec
 [57, 97, 99, 101, 113, 114, 115, 128, 129, 154, 185, 186, 196, 210, 212, 214, 215, 226, 243, 269, 282, 299, 309, 311, 314, 315, 325, 328, 340, 344, 366, 371, 397, 408, 412, 422, 424, 425, 426, 429, 443, 453, 457, 465, 468, 494, 500, 511, 521, 530, 537, 540, 554, 557, 578, 583, 593, 597, 608, 614, 634, 643, 658, 668, 669, 680, 691, 706, 711, 712, 715, 723, 740, 771, 779, 797, 809, 812, 819, 820, 826, 828, 855, 868, 877, 892, 908, 923, 925, 927, 983, 1005, 1021, 1022, 1024, 1040, 1111, 1123, 1134, 1135, 1137, 1168, 1191, 1234, 1236, 1248, 1252, 1265, 1320, 1333, 1349, 1380, 1434, 1446, 1448, 1462, 1477, 1535, 1559, 1561, 1576, 1648, 1674, 1689, 1745, 1802, 1860, 1988] 128
P2 Spec
 [57, 97, 99, 101, 113, 114, 115, 128, 129, 154, 185, 186, 196, 210, 212, 214, 215, 226, 243, 269, 282, 299, 300, 309, 311, 314, 315, 325, 328, 340, 344, 366, 397, 408, 412, 422, 424, 425, 426, 429, 443, 453, 457, 465, 494, 510, 511, 512, 521, 530, 537, 540, 554, 557, 578, 593, 607, 608, 609, 611, 634, 

---
**Problem #5:** (5 points) Of the three peptide sequences given in *Problem #2*, which has the fewest private peaks, and how many does it have?

In [6]:
union_peaks = set(p1_spec)|set(p2_spec)|set(p3_spec)
print(union_peaks, len(union_peaks))


p1_diff = union_peaks-set(p1_spec)
print("Diff P1:\n", p1_diff, len(p1_diff))
p2_diff = union_peaks-set(p2_spec)
print("Diff P2:\n", p2_diff, len(p2_diff))
p3_diff = union_peaks-set(p3_spec)
print("Diff P3:\n", p3_diff, len(p3_diff))


{1024, 512, 510, 1031, 521, 1034, 1545, 526, 1040, 530, 1559, 1531, 537, 1561, 1562, 540, 1563, 542, 1061, 1063, 1576, 1065, 554, 1535, 1066, 557, 57, 578, 583, 593, 597, 1111, 607, 608, 97, 609, 99, 1123, 101, 614, 611, 1120, 1132, 1133, 1134, 1135, 1648, 113, 114, 115, 1137, 1644, 1144, 634, 1660, 639, 128, 129, 643, 1160, 1674, 1163, 1162, 1677, 655, 1168, 658, 1176, 1689, 154, 668, 669, 1191, 680, 691, 185, 186, 1217, 706, 196, 708, 711, 712, 715, 1745, 210, 723, 212, 1234, 214, 215, 1236, 722, 725, 1245, 1246, 1248, 736, 226, 740, 1252, 1773, 1262, 1774, 752, 1265, 754, 243, 1273, 1277, 771, 1802, 779, 269, 282, 797, 805, 1319, 1320, 809, 299, 812, 300, 1330, 819, 820, 309, 1333, 311, 821, 822, 314, 315, 826, 828, 823, 1345, 1860, 325, 1349, 328, 1359, 1874, 851, 340, 853, 854, 855, 344, 1374, 1375, 1887, 865, 868, 1380, 877, 366, 371, 892, 908, 397, 918, 1431, 408, 920, 1434, 923, 412, 925, 927, 422, 1446, 424, 425, 426, 1448, 934, 429, 937, 427, 1458, 948, 1462, 951, 443, 1988, 

---
**Problem 6:** (5 points) Given the following experimental spectrum:

    experimental = [57, 97, 99, 101, 113, 114, 115, 128, 129, 154, 185, 186, 196, 
                    210, 212, 214, 215, 226, 243, 269, 299, 309, 311, 314, 315, 325, 
                    328, 340, 344, 366, 371, 397, 408, 412, 422, 424, 425, 426, 429,
                    443, 453, 457, 465, 468, 494, 500, 511, 521, 530, 537, 540, 554, 
                    557, 578, 583, 593, 597, 608, 614, 634, 643, 658, 668, 669, 680,
                    691, 706, 711, 712, 715, 723, 740, 771, 779, 797, 809, 812, 819,
                    820, 826, 828, 868, 877, 892, 908, 923, 925, 927, 983, 1005, 1021, 
                    1022, 1024, 1030, 1040, 1111, 1123, 1134, 1135, 1168, 1191, 1234, 
                    1236, 1250, 1252, 1265, 1320, 1328, 1333, 1349, 1380, 1434, 1446, 
                    1448, 1462, 1477, 1535, 1559, 1576, 1648, 1674, 1689, 1743, 1745, 
                    1860, 1988]

Which of the three given peptide sequences most likely produced it? Explain your reasoning.

In [7]:
experimental = [57, 97, 99, 101, 113, 114, 115, 128, 129, 154, 185, 186, 196, 
                210, 212, 214, 215, 226, 243, 269, 299, 309, 311, 314, 315, 325, 
                328, 340, 344, 366, 371, 397, 408, 412, 422, 424, 425, 426, 429,
                443, 453, 457, 465, 468, 494, 500, 511, 521, 530, 537, 540, 554, 
                557, 578, 583, 593, 597, 608, 614, 634, 643, 658, 668, 669, 680,
                691, 706, 711, 712, 715, 723, 740, 771, 779, 797, 809, 812, 819,
                820, 826, 828, 868, 877, 892, 908, 923, 925, 927, 983, 1005, 1021, 
                1022, 1024, 1030, 1040, 1111, 1123, 1134, 1135, 1168, 1191, 1234, 
                1236, 1250, 1252, 1265, 1320, 1328, 1333, 1349, 1380, 1434, 1446, 
                1448, 1462, 1477, 1535, 1559, 1576, 1648, 1674, 1689, 1743, 1745, 
                1860, 1988]

exp = set(experimental)
p1_s = set(p1_spec)
p2_s = set(p2_spec)
p3_s = set(p3_spec)

print("Diff p1\n", len(exp-p1_s))
print("Diff p1\n", len(p1_s-exp))

print("Diff p2\n", len(exp-p2_s))
print("Diff p2\n", len(p2_s-exp))

print("Diff p3\n",len(exp-p3_s))
print("Diff p3\n", len(p3_s-exp))


Diff p1
 4
Diff p1
 6
Diff p2
 42
Diff p2
 43
Diff p3
 44
Diff p3
 43


---
**Problem #7.** (5 points) The following question assumes the definitions of *breakpoint* and *strip* used in the discussion of reversal sorting from Lectures 24 to 25. Moreover, you should assume all permutations are extended (i.e. sandwiched between the fixed elements 0 and n+1). Is it possible to have a permutation of ***N*** elements with exactly 2 breakpoints where those breakpoints are both sides of a single element? Give an example, or explain why not.

---
**Problem #8:** (10 points) Consider two genomes with homologous genes, represented as letters, in the following orders:
```python
    G1 = "B,L,O,H,G,N,D,K,F,J,A,C,P,Q,M,E,I"
    G2 = "C,B,A,D,P,K,N,L,E,H,G,M,O,F,I,Q,J"
```
Find a series of reversals that transforms G1 to G2, where a reversal is given by the following function:
```python
    def reverse(genome,i,j):
        gene = genome.split(',')
        return ','.join(gene[:i] + [g for g in reversed(gene[i:j])] + gene[j:])
```        
Where the series of reversals
```python
    R1 = reverse(G1,1,11)
    R2 = reverse(R1,0,11)
    R3 = reverse(R2,0,12)
    print(R3)
```
produces:

    "C,B,A,J,F,K,D,N,G,H,O,L,P,Q,M,E,I"

Provide your series of reversals below. More credit will be given for fewer reversals. 

In [8]:
G1 = "BLOHGNDKFJACPQMEI"
G2 = "CBADPKNLEHGMOFIQJ"
print(len(G2))
conv_dict = {}
for i in range(len(G2)):
    conv_dict[G2[i]] = i+1
print(conv_dict)
number_list = []
for i in range(len(G1)):
    number_list.append(conv_dict[G1[i]])
print(number_list)
def hasBreakpoints(seq):
    """ returns True if sequences is not strictly increasing by 1 """
    for i in range(1, len(seq)):
        if (seq[i] != seq[i-1] + 1):
            return True
    return False

def getStrips(seq):
    """ find contained intervals where sequence is ordered, and return intervals
    in as lists, increasing and decreasing. Single elements are considered
    decreasing. "Contained" excludes the first and last interval. """
    deltas = [seq[i+1] - seq[i] for i in range(len(seq)-1)]
    increasing = list()
    decreasing = list()
    start = 0
    for i, diff in enumerate(deltas):
        if (abs(diff) == 1) and (diff == deltas[start]):
            continue
        if (start > 0):
            if deltas[start] == 1:
                increasing.append((start, i+1))
            else:
                decreasing.append((start, i+1))
        start = i+1
    return increasing, decreasing
def pickReversal(seq, strips):
    """ test each decreasing interval to see if it leads to a reversal that
    removes two breakpoints, otherwise, return a reversal that removes only one """
    for i, j in strips:
        k = seq.index(seq[j-1]-1)
        if (seq[k+1] + 1 == seq[j]):
            # removes 2 breakpoints
            return 2, (min(k+1, j), max(k+1, j))
    # In the worst case we remove only one, but avoid the length "1" strips
    for i, j in strips:
        k = seq.index(seq[j-1]-1)
        if (j - i > 1):
            break
    return 1, (min(k+1, j), max(k+1, j))

def doReversal(seq,reversal):
    i, j = reversal
    return seq[:i] + [element for element in reversed(seq[i:j])] + seq[j:]

def improvedBreakpointReversalSort(seq, verbose=True):
    seq = [0] + seq + [max(seq)+1]                             # Extend sequence
    N = 0
    while hasBreakpoints(seq):
        increasing, decreasing = getStrips(seq)
        if len(decreasing) > 0:                                # pick a reversal that removes a decreasing strip
            removed, reversal = pickReversal(seq, decreasing)
        else:
            removed, reversal = 0, increasing[0]               # No breakpoints can be removed
        if verbose:
            print("Strips:", increasing, decreasing)
            print("%d: %s  rho%s" % (removed, seq, reversal))
            input("Press Enter:")
        seq = doReversal(seq,reversal)
        N += 1
    if verbose:
        print(seq, "Sorted")
    return N

# Also try: [1,9,3,4,7,8,2,6,5]
print()
print(improvedBreakpointReversalSort(number_list, verbose=True))

17
{'C': 1, 'B': 2, 'A': 3, 'D': 4, 'P': 5, 'K': 6, 'N': 7, 'L': 8, 'E': 9, 'H': 10, 'G': 11, 'M': 12, 'O': 13, 'F': 14, 'I': 15, 'Q': 16, 'J': 17}
[2, 8, 13, 10, 11, 7, 4, 6, 14, 17, 3, 1, 5, 16, 12, 9, 15]

Strips: [(4, 6)] [(1, 2), (2, 3), (3, 4), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (12, 13), (13, 14), (14, 15), (15, 16), (16, 17), (17, 18)]
2: [0, 2, 8, 13, 10, 11, 7, 4, 6, 14, 17, 3, 1, 5, 16, 12, 9, 15, 18]  rho(4, 16)
Press Enter:
Strips: [] [(1, 2), (2, 3), (3, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (12, 13), (13, 14), (14, 17), (17, 18)]
2: [0, 2, 8, 13, 12, 16, 5, 1, 3, 17, 14, 6, 4, 7, 11, 10, 9, 15, 18]  rho(1, 8)
Press Enter:
Strips: [(4, 6), (7, 9)] [(2, 3), (3, 4), (6, 7), (9, 10), (10, 11), (11, 12), (12, 13), (13, 14), (14, 17), (17, 18)]
1: [0, 1, 5, 16, 12, 13, 8, 2, 3, 17, 14, 6, 4, 7, 11, 10, 9, 15, 18]  rho(7, 17)
Press Enter:
Strips: [(4, 6), (6, 10)] [(2, 3), (3, 4), (10, 11), (11, 12), (12, 13), (13, 14), (14, 15), (15

---
The start of most mammalian genes are associated with promoter regions that exhbit a higher than expected occurance of *CG* dinucleotides. These regions are called ***"CG-islands"***. Assume a simplified hidden-Markov model of a genome which alternates betten two states, normal (<b>N</b>) and CG-island (<b>I</b>), as depicted below:  

<div align="center"><img src="http://csbio.unc.edu/mcmillan/Comp555S18/Media/FinalCGHMM.png" width="400px"></div>

---
**Problem #9.** (10 points) How many Cs or Gs within a window of length *n* would imply that you are most likely within a CG-island?

---
**Problem 10.** (5 points) The following graph shows the Log-Odds of $P(b_i | N)$ over $P(b_i | I)$ for the sequence shown along the x-axis computed in two ways. 
<br><br>

<div align="center"><img src="http://csbio.unc.edu/mcmillan/Comp555S18/Media/FinalLogOdds.png" width="800px"></div>

The blue line is based on ratios from the Forward-Backward solution at every base, and the gold line is based on a 7-base window (extending 3-bases on both sides of the plotted point) assuming a state sequence of "NNNNNNN" and "IIIIIII". Use this inforamtion to predict the hidden state for each base of the given 50-base sequence.  

---
**Problem 11.** (5 points) How does the likelihood of your state predictions from problem 10 compare to the actual series of states used to generate the given base sequence shown below?

                             |    |    |    |    |    |    |    |    |    |
            sequence:    TCATAATCTGGGGGTCGGCGCGGGGGGCCGGACGGCTCACGATGTACTTG
            NI-state:    NNNNNNNNNNNIIIIIIIIIIIIIIIIIIIIIIIIIINNNNNNNNNIIII

What does this imply?

---
**Problem #12.** (5 points) Produce a series of state predictions that is *unlikely* to have produced the given base sequence from problems 10 and 11. Explain why?

In [9]:
NI_list = ['N', 'I', 'N', 'N', 'I', 'I', 'I', 'N', 'I', 'I', 'I', 'I', 'N', 'N', 'N', 'N', 'N', 'I', 'I', 'I', 'N', 'I', 'N', 'N', 'I', 'I', 'I', 'I', 'N', 'N', 'N', 'N', 'N', 'N', 'I', 'I', 'I', 'I', 'N', 'N', 'N', 'I', 'I', 'I', 'I', 'I', 'N', 'I', 'I', 'N', 'N']
NI_s = ""
for i in NI_list:
    NI_s+= i
print(NI_s)

NINNIIINIIIINNNNNIIININNIIIINNNNNNIIIINNNIIIIINIINN


---
**Problem #13.** (5 points) What is the smallest value of <i>k</i> where the number of possible <i>k</i>-mer motif positions within 10 DNA strands of length 100 is less than the number of possible <i>k</i>-mers? 

In [ ]:
def kmerCounts(seq, k):
    kmerDict = {}
    for i in range(1,len(seq)-k+1):
        kmer = seq[i:i+k]
        kmerDict[kmer] = kmerDict.get(kmer,0) + 1
    return kmerDict

print('  k     k-mers              4^k      N-k+1          missing   repeated')
for k in range(2,25):
    kmers = kmerCounts(seq, k)
    print("%3d %10d %16d %10d %16d %10d" % (k, len(kmers), 4**k, (len(seq)-1)-k+1, 4**k-len(kmers), (len(seq)-1)-k+1-len(kmers)))
    
kmers = kmerCounts(seq, 4)
    
def printAllKLength(set, k): 
    n = len(set)  
    printAllKLengthRec(set, "", n, k) 
  
def printAllKLengthRec(set, prefix, n, k): 
    # Base case: k is 0, 
    # print prefix 
    if (k == 0) : 
#         print(prefix)
        all_kmers.append(prefix)
        return
  
    # One by one add all characters  
    # from set and recursively  
    # call for k equals to k-1 
    for i in range(n): 
  
        # Next character of input added 
        newPrefix = prefix + set[i] 
          
        # k is decreased, because  
        # we have added a new character 
        printAllKLengthRec(set, newPrefix, n, k - 1)
all_kmers = []
set1 = ['A','C','G','T']
printAllKLength(set1, 4)
# print(all_kmers)
print("\n\n4 missing kmers:")
print(list(set(all_kmers) - set(kmers)))

---
**Problem #14.** (5 points) Which of the following is larger an uncompressed msBWT that indexes 100 DNA sequences each of length 100 or the suffix array over the same 100 DNA sequences?

---
**Problem #15.** (5 points) Which in-class exercise was a trap?

---
**Last Call:** If you have any remaining issues with problem set grades describe them in the following cell. Indicate clearly the *problem set* and the *problem number* for each issue.